---
version: "3.7"
services:
  tls:
    # note on versioning: even minor numbers are stable, odd are mainline/development
    image: nginx:1.24.0
    volumes:
      - ./tls/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./tls/ca.cert.pem:/etc/nginx/ca.cert.pem
      - ./tls/server.cert.pem:/etc/nginx/server.cert.pem
      - ./tls/server.key.pem:/etc/nginx/server.key.pem
    ports:
      - "5600:5600"
    depends_on:
      - authn

  authn:
    image: ghcr.io/ccatobs/authn-proxy/authn-proxy:v1.0.2
    environment:
      - "GITHUB_ORG=ccatobs"
      - "PORT=8000"
      - "UPSTREAMS=/=http://web:8000,/api/v1=http://api:8000,/grafana=http://grafana:3000"
    depends_on:
      - api
      - grafana
      - web

  api:
    build: ./api
    depends_on:
      - tcs

  tcs:
    image: ghcr.io/ccatobs/telescope-control-system/telescope-control-system:2024-02-24
    environment:
      - FYST_ACU_HOST=acu

  web:
    build: ./web
    environment:
      - "MIX_ENV=prod"
      - "PORT=8000"
    depends_on:
      - api

  grafana:
    image: grafana/grafana-oss:9.5.7
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./loki/grafana-datasource.yml:/etc/grafana/provisioning/datasources/loki.yml

  loki:
    image: grafana/loki:2.8.4

  vector:
    image: timberio/vector:0.29.1-debian
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki

